# SPDX-FileCopyrightText: 2023 Sidings Media
# SPDX-License-Identifier: MIT

openapi: 3.0.3
info:
  title: Sidings Media API
  description: |
      General utility APIs for all Sidings Media web based services
  version: 0.1.3


servers:
  - url: http://localhost:{port}
    description: Local development
    variables:
      port:
        default: "3000"
  - url: https://api.sidingsmedia.com/
    description: Production


components:
  schemas:
    Message:
      type: object
      properties:
        name:
          type: string
          description: Users name from contact form
        email:
          type: string
          format: email
          description: Users email from contact form
        subject:
          type: string
          description: Message subject
        message:
          type: string
          description: Actual message from user
      required:
        - name
        - email
        - subject
        - message

    GeneralError:
      type: object
      properties:
        code:
          type: integer
          description: HTTP response code
        message:
          type: string
          description: Human readable error message

    BadRequest:
      type: object
      properties:
        code:
          type: integer
          description: HTTP response code
        message:
          type: string
          description: Human readable error message
        fields:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                description: Name of field
              condition:
                type: string
                description: |
                  The condition that caused the binding to fail

  responses:
    BadRequest:
      description: Request was invalid or malformed
      content:
        application/json:
          schema:
            oneOf:
              - $ref: "#/components/schemas/GeneralError"
              - $ref: "#/components/schemas/BadRequest"
          example:
            code: 400
            message: Request was malformed
            fields:
              - field: email
                condition: email
              - field: name
                condition: required

    TooManyRequests:
      description: The rate limit has been exceeded
      headers:
        Retry-After:
          schema:
            type: integer
          description: |
            Number of seconds until the client should retry the request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GeneralError"
          example:
            code: 429
            message: Too many requests

    ServerError:
      description: An unexpected server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GeneralError"
          example:
            code: 500
            message: Unexpected error


tags:
  - name: messaging
    description: |
      Communication channels between Sidings Media and the User


paths:
  /messaging/contact:
    post:
      description: Send a message to Sidings Media
      tags:
        - messaging
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"
      responses:
        204:
          description: Created

        400:
          $ref: "#/components/responses/BadRequest"

        429:
          $ref: "#/components/responses/TooManyRequests"

        5XX:
          $ref: "#/components/responses/ServerError"
